apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-gitlab
  namespace: gitlab-cicd
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etc-gitlab
  namespace: gitlab-cicd
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-gitlab
  namespace: gitlab-cicd
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: gitlab-cicd
  labels:
    name: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gitlab
  template:
    metadata:
      name: gitlab
      labels:
        name: gitlab
    spec:
      containers:
        - name: gitlab
          image: gitlab/gitlab-ce:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: GITLAB_TIMEZONE
              value: Beijing
            - name: GITLAB_SECRETS_DB_KEY_BASE
              value: long-and-random-alpha-numeric-string
            - name: GITLAB_SECRETS_SECRET_KEY_BASE
              value: long-and-random-alpha-numeric-string
            - name: GITLAB_SECRETS_OTP_KEY_BASE
              value: long-and-random-alpha-numeric-string
            - name: GITLAB_ROOT_PASSWORD
              value: admin123456
            - name: GITLAB_ROOT_EMAIL
              value: songli@qq.com
            - name: GITLAB_HOST
              value: gitlab.imind.tech
            - name: GITLAB_PORT
              value: "80"
            - name: GITLAB_SSH_PORT
              value: "22"
            - name: GITLAB_NOTIFY_ON_BROKEN_BUILDS
              value: "true"
            - name: GITLAB_NOTIFY_PUSHER
              value: "false"
            - name: GITLAB_BACKUP_SCHEDULE
              value: daily
            - name: GITLAB_BACKUP_TIME
              value: 01:00
            - name: GITLAB_OMNIBUS_CONFIG
              value: |
                ## time_zone
                gitlab_rails['time_zone'] = 'Asia/Shanghai'
                ## postgres
                postgresql['enable'] = false
                gitlab_rails['db_adapter'] = "postgresql"
                gitlab_rails['db_encoding'] = "utf-8"
                gitlab_rails['db_database'] = "gitlab"
                gitlab_rails['db_username'] = "postgres"
                gitlab_rails['db_password'] = "xxx"
                gitlab_rails['db_host'] = "postgres-svc"
                gitlab_rails['db_port'] = 5432
                ## redis
                redis['enable'] = false
                gitlab_rails['redis_host'] = "redis"
                gitlab_rails['redis_port'] = 6379
                #gitlab_rails['redis_password'] = "redis_password"
                gitlab_rails['redis_database'] = 0
                ## pages
                pages_external_url "http://page.imind.tech/"
                gitlab_pages['enable'] = true
                gitlab_rails['pages_path'] = "/var/opt/gitlab/pages"
                gitlab_pages['external_http'] = ['1.1.1.2:80']
                #gitlab_pages['access_control'] = true
                ## gitlab ssh,http克隆地址，默认为hostname
                external_url "http://gitlab.imind.tech/"
                ## email setting
                gitlab_rails['smtp_enable'] = true
                gitlab_rails['smtp_address'] = "smtp.qq.com"
                gitlab_rails['smtp_port'] = 465
                gitlab_rails['smtp_user_name'] = "songli@qq.com"
                gitlab_rails['smtp_password'] = "xxx"
                gitlab_rails['smtp_authentication'] = "login"
                gitlab_rails['smtp_enable_starttls_auto'] = true
                gitlab_rails['smtp_tls'] = true
                gitlab_rails['gitlab_email_from'] = 'songli@qq.com'
                gitlab_rails['smtp_domain'] = "smtp.qq.com"
                postgresql['enable'] = false
                postgres_exporter['enable'] = false
                redis['enable'] = false
                prometheus['enable'] = false
                alertmanager['enable'] = false
                node_exporter['enable'] = false
                redis_exporter['enable'] = false
                prometheus_monitoring['enable'] = false
          ports:
            - name: http
              containerPort: 80
            - name: ssh
              containerPort: 22
          volumeMounts:
            - mountPath: /var/log/gitlab
              name: log-gitlab
            - mountPath: /etc/gitlab
              name: etc-gitlab
            - mountPath: /var/opt/gitlab
              name: data-gitlab
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 900
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 1
      volumes:
        - name: data-gitlab
          persistentVolumeClaim:
            claimName: data-gitlab
        - name: etc-gitlab
          persistentVolumeClaim:
            claimName: etc-gitlab
        - name: log-gitlab
          persistentVolumeClaim:
            claimName: log-gitlab

---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: gitlab-cicd
  labels:
    name: gitlab
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: ssh
      port: 22
      targetPort: ssh
  selector:
    name: gitlab

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gitlab
  namespace: gitlab-cicd
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`gitlab.imind.tech`)
      kind: Rule
      services:
        - name: gitlab
          port: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitlab
  namespace: gitlab-cicd
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
spec:
  rules:
    - host: gitlab.imind.tech
      http:
        paths:
          - backend:
              service:
                name: gitlab
                port:
                  number: 80
            path: /